version: '3.8'
services:
  backend:
    build: ./backend
    environment:
      - NODE_ENV=development
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
