# .github/workflows/backend.yml
name: Deploy Node to ECS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build Docker image
        run: |
          docker build -t react-node-backend backend
          docker tag react-node-backend:latest <account-id>.dkr.ecr.us-east-1.amazonaws.com/react-node-backend:latest
      - name: Push Docker image
        run: |
          docker push <account-id>.dkr.ecr.us-east-1.amazonaws.com/react-node-backend:latest
      - name: Update ECS service
        run: |
          aws ecs update-service --cluster react-node-cluster --service react-node-backend-service --force-new-deployment

