name: Frontend Deploy

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::YOUR_ACCOUNT_ID:role/my-github-actions-role
          aws-region: us-east-1

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Upload to S3
        run: |
          BUCKET=$(aws ssm get-parameter --name "/my-react-node-app-frontend/s3_bucket" --query "Parameter.Value" --output text)
          aws s3 sync frontend/build/ s3://$BUCKET/ --delete

      - name: Invalidate CloudFront
        run: |
          DIST_ID=$(aws ssm get-parameter --name "/my-react-node-app-frontend/cloudfront_id" --query "Parameter.Value" --output text)
          aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"

