name: Frontend Deploy

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Upload to S3
        run: |
          BUCKET=$(aws ssm get-parameter --name "/my-react-node-app/s3_bucket" --query "Parameter.Value" --output text)
          aws s3 sync frontend/build/ s3://$BUCKET/ --delete

      - name: Invalidate CloudFront
        run: |
          DIST_ID=$(aws ssm get-parameter --name "/my-react-node-app/cloudfront_id" --query "Parameter.Value" --output text)
          aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"

