name: Provision Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
      
      - name: Check Terraform formatting
        run: terraform fmt -check
      
      - name: Terraform Init
        run: terraform init -upgrade

      - name: Validate Terraform
        run: terraform validate
      
      - name: Terraform Plan
        run: terraform plan -var-file=dev.tfvars

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=dev.tfvars

